- README.rst
- environment_dev.yml
- requirements_dev.txt
- setup.py
- src/py21cmfast/__init__.py
- src/py21cmfast/__main__.py
- src/py21cmfast/_utils.py
- src/py21cmfast/cache_tools.py
- src/py21cmfast/cli.py
- src/py21cmfast/plotting.py
- src/py21cmfast/wrapper.py
- tox.ini
Set version to 3.0.0dev (to be bumped to 3.0.0 when we are happy with the overall API) and set PyPI name to 21cmFAST.
> specify initial version and PyPI name

- src/py21cmfast/src/GenerateICs.c
> fixed 2LPT bug

- src/py21cmfast/wrapper.py
- tests/produce_integration_test_data.py
- tests/test_wrapper.py
An attempt to make the new `Coeval` class a bit nicer to work with.
Addresses #52 .
Inviting feedback on the API!
> Make Coeval nicer to work with

- src/py21cmfast/wrapper.py
> Move perturb check up in the function

- .travis.yml
- tox.ini
Separate linting job from the other tests.
Fixes #72
> Separate linting

- src/py21cmfast/wrapper.py
> Use write/regen/direc in run_coeval and run_lightcone

- src/py21cmfast/src/IonisationBox.c
we need to initialize z_res_box
> initialize z_res_box

- src/py21cmfast/wrapper.py
> Better z re

- CHANGELOG.rst
- src/py21cmfast/__init__.py
- src/py21cmfast/_utils.py
- src/py21cmfast/src/21cmFAST.h
- src/py21cmfast/src/BrightnessTemperatureBox.c
- src/py21cmfast/src/FindHaloes.c
- src/py21cmfast/src/GenerateICs.c
- src/py21cmfast/src/IonisationBox.c
- src/py21cmfast/src/PerturbField.c
- src/py21cmfast/src/SpinTemperatureBox.c
- src/py21cmfast/src/exceptions.h
- src/py21cmfast/wrapper.py
I have refactored the code for creating the FFTW Wisdoms. Originally the C code would first check to see if the wisdom exists, if it didn't it would create it. Now, there is a separate function for creating FFTW Wisdoms, which will do exactly the same.
Basically, this minimises redundant code.
> Refactor fftw wisdoms

- .isort.cfg
- .pre-commit-config.yaml
- INSTALLATION.rst
- README.rst
- build_cffi.py
- devel/TestFindHalos.py
- devel/simulate_mcmc_memory_leak.py
- setup.py
- src/py21cmfast/__init__.py
- src/py21cmfast/_utils.py
- src/py21cmfast/cache_tools.py
- src/py21cmfast/cli.py
- src/py21cmfast/inputs.py
- src/py21cmfast/outputs.py
- src/py21cmfast/plotting.py
- src/py21cmfast/wrapper.py
- tests/conftest.py
- tests/produce_integration_test_data.py
- tests/test_cache_tools.py
- tests/test_cli.py
- tests/test_config.py
- tests/test_exceptions.py
- tests/test_high_level_io.py
- tests/test_initial_conditions.py
- tests/test_input_structs.py
- tests/test_integration_features.py
- tests/test_output_structs.py
- tests/test_wrapper.py
Adds a note that the package can be installed with `conda`.
Fixes #45
> doc: add note about installing using conda-forge

- INSTALLATION.rst
- README.rst
- docs/tutorials/coeval_cubes.ipynb
- src/py21cmfast/_utils.py
- src/py21cmfast/cli.py
- src/py21cmfast/outputs.py
- src/py21cmfast/plotting.py
- user_data/runconfig_example.yml
This PR attempts to address most/all of the comments from @sultanier
at https://github.com/openjournals/joss-reviews/issues/2582.
It adds some documentation on simple usage, especially the CLI, to the readme,
fixes a couple of issues with the CLI, and adds the ability to output the full
Coeval/Lightcone objects created.
Partially resolves #81 by defining a `Coeval.get_fields` method which can be run as a classmethod to obtain the different "kinds" that are plot-able.
> Address Sultan's Comments on Paper

- joss-paper/paper.bib
- joss-paper/paper.md
I've made a few small formatting changes to the paper as a final round of edits for https://github.com/openjournals/joss-reviews/issues/2582
> Small edits to the manuscript for JOSS

- joss-paper/make_the_paper.sh
- joss-paper/paper.md
Some simple fixes to the formatting of the JOSS paper, only noticeable once I could compile it properly (hence new branch name).
> doc: some formatting fixes in the joss paper

- README.rst
Adds JOSS badge for new paper, and makes the acknowledgments section a bit clearer.
Looking for input on other features included in the code that should be cited explicitly if used.
Fixes #4.
> Add Acknowledgment Refs

- devel/simulate_mcmc_memory_leak_lightcone.py
- environment_dev.yml
> remove mkl to fix fft bug in mkl_fft

- src/py21cmfast/_utils.py
Just adds the existing error code to the list of raisable errors.
> fix: adds the infinity or nan error to the list

- docs/design.rst
> doc: update design philosophy docs

- docs/faqs/misc.rst
> Add docs for lightcone/coeval disk format

- .github/workflows/publish-to-pypi.yaml
- .github/workflows/test_suite.yaml
- CHANGELOG.rst
- src/py21cmfast/src/heating_helper_progs.c
Removal of a couple of embedded functions that were causing issues for the conda package build for MacOS
> Remove embedded functions causing issues for conda package

- .pre-commit-config.yaml
- src/py21cmfast/_utils.py
- src/py21cmfast/inputs.py
- src/py21cmfast/wrapper.py
> fix: allow passing dicts to wrapper functions

- src/py21cmfast/_cfg.py
- src/py21cmfast/cache_tools.py
- src/py21cmfast/cli.py
- src/py21cmfast/wrapper.py
> fix: spurious warning on config setup

- src/py21cmfast/plotting.py
Small change allowing `plotting.lightcone_sliceplot` to have a minimum redshift without messing with the lightcone object itself. For when you want to only plot a subset of cosmic history.
> add a minimum z to lightcone_sliceplot

- src/py21cmfast/src/IonisationBox.c
The inhomogeneous recombinations model has an error check which exits when a non-finite recombination rate is found. since the refactor of `Ionisationbox.c`, this error flag was used uninitialised, which caused problems when debug mode was enabled, throwing an error occasionally without a non-finite value.
I have also added a log entry when the error is triggered. Since the error causes an exit after the loop, this shouldn't print too many times.
> Fix recombinations error flag

- src/py21cmfast/io/caching.py
- src/py21cmfast/io/h5.py
- tests/test_caching.py
This adds a few improvements to the `RunCache` class, as well as a bunch of tests.
I wrote this because I realized that there were errors in the `get_all_boxes_at_z` method, and I also wanted an easy way to output a `Coeval` from this.
> test: add tests for the RunCache

- src/py21cmfast/src/SpinTemperatureBox.c
fixed segfault bug without halos but with minihalos and no lya heating
> fixed segfault bug without halos but with minihalos and no lya heating

- src/py21cmfast/src/SpinTemperatureBox.c
- src/py21cmfast/wrapper/outputs.py
This change was made to reduce used memory when `USE_MINI_HALOS=False`.
> J_21_LW exists only if USE_MINI_HALOS=True

- .github/workflows/base_benchmarks.yml
> Add base benchmark

- src/py21cmfast/src/HaloBox.c
This change was made in order to calculate more accurately the emissivity fields in `HaloBox` in the (rare) configuration of `FIXED_HALO_GRIDS=False`, `HALO_STOCHASTICITY=False` and `AVG_BELOW_SAMPLER=True`. Now, the upper mass integral limit for the unresolved halos corresponds to the (highres) cell size, in agreement with the smallest scale in the DEXM algorithm in this configuration.
> changed upper mass integral limit when HALO_STOCHASTICITY=False

- README.rst
- src/py21cmfast/utils.py
- tests/test_utils.py
This updates the readme to include the v4 paper and adds a function which prints out relevant papers depending on input parameters
> update readme, make reference printing function

- .github/workflows/base_benchmarks.yml
Part 1 of the probable fix to #515. setting up the benchmarks on the main branch
> change benchmark branch to main

- .github/workflows/base_benchmarks.yml
- .github/workflows/bencher-archive-closed.yml
- .github/workflows/pr_benchmarks.yml
> run benchmarks on main
