21cmfast/21cmFAST

- tox.ini
Enables python to print out a stack trace during tests when a `SEGFAULT` or similar is encountered. Since we are using a lot of C backend code, this should come in handy.
Closes #6.
> Enable pythons fault handler on tests

- .flake8
- src/py21cmfast/src/21cmFAST.h
- src/py21cmfast/src/ps.c
- src/py21cmfast/wrapper.py
- tests/test_wrapper.py
This PR adds a `Coeval` class, a list of which is what is returned by `run_coeval`. This makes it easier to digest the output of `run_coeval` (originally written as a fix to the problem introduced in `PhotonCons` in where the return values had to be defined). 
It also adds a docstring to `get_photon_nonconservation_data`.
It also adds a `photoncons_inited` variable to the C globals, which can be accessed by Python -- in  `get_photon_nonconservation_data`, it returns None if this is False. Otherwise, this function can be called any time and will give garbage.
> Add Coeval class to make run_coeval more homogeneous

- CONTRIBUTING.rst
- docs/contributing.rst
- docs/index.rst
- docs/notes_for_developers.rst
- environment_dev.yml
This PR makes the `CONTRIBUTING.rst` a bit better. 
Now it leads the new developer through the exact process required to get setup (and also serves as a good memory-jog for us others). It also points directly to the developer documentation for more details (those docs also link back the to the contributing). 
I figure it would be good to get @andreimesinger to have a quick read through, as someone who hasn't used the new setup very much, to see if it makes sense and suggest changes.
Fixes #65
> Contributing

- src/py21cmfast/_utils.py
- src/py21cmfast/src/21cmFAST.h
- src/py21cmfast/src/BrightnessTemperatureBox.c
- src/py21cmfast/wrapper.py
- tests/test_spin_temp.py
Fixes #59 .
The issue was that the passed `TsBox` at `Z_HEAT_MAX` was not expected to be used -- therefore it was being set at a very minimal level, and its initialization used default `user_params`. If the dimensions were smaller than those actually being used, it would error due to invalid write. 
This is fixed here, and I added a test. I also added the ability to have proper "dummy" boxes that don't get initialized at all if they're not used, to conserve memory. 
This will be merged into `doc-updates` (it was branched off that).
> Fix issue with first box and add test

- src/py21cmfast/src/ps.c
Fixed #91 
There was a kink on LFs when F_STAR(M_h) crosses unity. 
To remove this kink, added the interpolation of the derivative (dMuvdMhalo) in a range where the kink appears.
Most of the cases the kinks are smoothed out but in some cases with ALPHA_STAR < -0.5 it doesn't work. However, because ALPHA_STAR < -0.5 is not physical (at least when we consider observations of LFs), this modification is ok.
Attached an example file.
[LF_test-1.pdf](https://github.com/21cmfast/21cmFAST/files/4224455/LF_test-1.pdf)
> LF calculation

- src/py21cmfast/src/ps.c
- src/py21cmfast/wrapper.py
Fixes #109 
Simple fix that the `init_ps` function wasn't being called when reading from cache, since initial conditions weren't being run.
It was hardish to locate, but will get easier once #64 is merged. 
It does bring up the point that there are some of these high-level global initialisation routines which we have to think more carefully about. My fix here was to run `init_ps` for every time we initialise photon cons, but that re-runs things that sometimes don't need to be. We've also run in to this error a few times when code's added, because it's very easy to forget that a function is dependent on `init_ps` having already been run, and assume that it has been.
@BradGreig any ideas?
Let's pull this fix in ASAP.
> Fix failing to do photon_cons when reading init from cache

- docs/notes_for_developers.rst
- src/py21cmfast/src/21cmFAST.h
- src/py21cmfast/src/BrightnessTemperatureBox.c
- src/py21cmfast/src/GenerateICs.c
- src/py21cmfast/src/Globals.h
- src/py21cmfast/src/IonisationBox.c
- src/py21cmfast/src/PerturbField.c
- src/py21cmfast/src/SpinTemperatureBox.c
- src/py21cmfast/src/UsefulFunctions.c
- src/py21cmfast/src/bubble_helper_progs.c
- src/py21cmfast/src/cexcept.h
- src/py21cmfast/src/elec_interp.c
- src/py21cmfast/src/exceptions.h
- src/py21cmfast/src/heating_helper_progs.c
- src/py21cmfast/src/ps.c
- src/py21cmfast/src/recombinations.c
- src/py21cmfast/wrapper.py
- tests/test_exceptions.py
- tests/test_initial_conditions.py
- tests/test_integration_features.py
This PR adds exception handling to C. 
The basic premise is that any non-API function (i.e. any function that's not in `21cmFAST.h`) should never just return an int to signal that it broke. Instead, it should do a `Throw <exception_kind>;`. 
The new `cexception.h` file includes the `Throw` macro. If this happens within a `Try {} Catch {}` block, the execurtion will jump to the `Catch` (at any level of the call stack). So these really are like `Try; Except; Raise` in Python. 
Any API-level function in C should be pretty much globally wrapped in a `Try Catch`, and if the `Catch` is activated, should return the error code to Python, which will then deal with it accordingly.
Closes #16.
This will go a long way to solving issues like #16 . In fact, this may solve that issue entirely, though …
> More rigorous exceptions

- .readthedocs.yml
- build_cffi.py
- docs/conf.py
- docs/environment.yaml
- docs/requirements.txt
- docs/tutorials.rst
- src/py21cmfast/__init__.py
- src/py21cmfast/_cfg.py
Fixes issues with compilation of the docs on readthedocs. See compiled docs here: https://21cmfast.readthedocs.io/en/readthedocs.
Fixes #136 
Also fixes a small bug in the `Config` class in which if `21cmFAST` was imported without installing it (i.e. this is what the readthedocs build does -- adds the directory to the PYTHONPATH to import it), it wouldn't find the config file. Now it does not _need_ that file -- it is based on defaults in the class itself if the file is not found.
> Readthedocs

- INSTALLATION.rst
- src/py21cmfast/wrapper.py
Just adds a note to the INSTALLATION.rst about minimum gcc version. We can't force this dependency in `setup.py` at all, so I think this is the extent of what we can do.
> Add note about gcc version

- src/py21cmfast/src/PerturbField.c
we need to free these arrays otherwise ram cumulates too much during mcmc
> free HIRES_density_perturb if PERTURB_ON_HIGH_RES

- src/py21cmfast/src/Globals.h
- src/py21cmfast/src/IonisationBox.c
- src/py21cmfast/src/ps.c
- src/py21cmfast/wrapper.py
This is in response to #144. I have added in the ability for the user to modify the end-point of the photon non-conservation correction calibration. Additionally, added in errors to `run_coeval` and `run_lightcone` to catch this condition as soon as possible.
As discussed in #144, I have added this functionality to `global_params` because it will be very rare for the user to ever need this behaviour.
@steven-murray, I have tagged you to make sure the errors to catch this condition I added make sense (or if there is a better way).
> Expand photoncons range

- docs/conf.py
- docs/environment.yaml
This PR fixes a few issues raised by @adampbeardsley in relation to documentation:
One page links here, which is broken: https://21cmfast.readthedocs.io/en/latest/reference/_autosummary/py21cmfast.inputs.html
And this page looks like it should have more to it?
https://21cmfast.readthedocs.io/en/latest/reference/py21cmfast.html
Looks like the builds are failing:
https://readthedocs.org/projects/21cmfast/builds/11176485/
This fixes all of those issues.
> docs: ensure matplotlib is installed for docs

- MANIFEST.in
- src/py21cmfast/__init__.py
- src/py21cmfast/inputs.py
This fixes issues that we're having with 21CMMC (see eg. https://github.com/21cmfast/21CMMC/pull/27) where it's not finding the external_tables. Turns out the error is due to the `MANIFEST.in` not recursively including the files. This doesn't error for 21cmFAST's Travis,  since it directly installs them from the repo, but it does error for 21cmMC, because it installs from PyPI (and the files are not being included in the dist that gets uploaded to PyPI). 
It also adds a little test to ensure that the user data folder properly exists and spit out a nicer error than that reported from the C.
> Some fixes for the external tables

- CHANGELOG.rst
- src/py21cmfast/__init__.py
- src/py21cmfast/src/FindHaloes.c
This PR just puts some function prototypes into `FindHaloes.c` which is necessary apparently to compile on default MacOSX compilers. This is mostly necessary to get the `conda` package working (https://github.com/conda-forge/staged-recipes/pull/11809)
> fix: make function prototypes

- src/py21cmfast/inputs.py
This PR attempts to fix the currently broken readthedocs builds.
They are breaking because no ~/.21cmfast directory can be made
on RTD, and the code errors on import when this is the case.
This fixes this -- by only erroring when trying to *use* stuff
in that directory, rather than just on import.
> fix: only raise error on non-available table-path when using it

- .gitignore
- CHANGELOG.rst
- docs/notes_for_developers.rst
- src/py21cmfast/_utils.py
- src/py21cmfast/inputs.py
- src/py21cmfast/src/BrightnessTemperatureBox.c
- src/py21cmfast/src/FindHaloes.c
- src/py21cmfast/src/GenerateICs.c
- src/py21cmfast/src/Globals.h
- src/py21cmfast/src/IonisationBox.c
- src/py21cmfast/src/PerturbField.c
- src/py21cmfast/src/PerturbHaloField.c
- src/py21cmfast/src/SpinTemperatureBox.c
- src/py21cmfast/src/UsefulFunctions.c
- src/py21cmfast/src/dft.c
- src/py21cmfast/src/indexing.c
- src/py21cmfast/wrapper.py
- tests/conftest.py
- tests/test_high_level_io.py
- tests/test_integration_features.py
This partly addresses #179 with a quick workaround where wisdoms are used if found, and otherwise don't produce an error, just a warning. 
More importantly, it removes a lot of boilerplate code from several C files, replacing it with a two simple functions in `dft.c`.
> Fix wisdoms

- MANIFEST.in
This simply includes the `tests/` directory in the source tarball that ends up on PyPI. This is useful for the `conda` build, which can then run some of the tests before deployment.
> maint: include tests in source tarball

- CHANGELOG.rst
- src/py21cmfast/outputs.py
- src/py21cmfast/src/21cmFAST.h
- src/py21cmfast/src/GenerateICs.c
- tests/test_initial_conditions.py
I re-used the HIRES_box variable to loop over the 3 v_cb directions and add them in quadrature directly to boxes->lowres_vcb. The high-res vcb box is never used, so there isn't much point in generating it.
This is fast and does not add any memory overload over a no-vcb run. The modification follows what was already in generateICs.c for the perturbation velocities, though with different k weightings (to track the power in vcb).
Plots attached are the old vcb both in lowres and hires (which look very similar as vcb has not power at small scales), and the new vcb. Which is identical to the old lowres.
> Updated generation of relvels to not require extra memory

- src/py21cmfast/src/GenerateICs.c
Code was crashing with "`PERTURB_ON_HIGH_RES`": True, because the `boxes->lowres_vcb` loop indices were set to `dimension` rather than `HII_DIM`
> Fixed relvel generation with hires PT

- src/py21cmfast/_utils.py
- src/py21cmfast/inputs.py
- src/py21cmfast/src/BrightnessTemperatureBox.c
- src/py21cmfast/src/IonisationBox.c
- src/py21cmfast/src/SpinTemperatureBox.c
- src/py21cmfast/src/UsefulFunctions.c
- src/py21cmfast/src/exceptions.h
- src/py21cmfast/src/heating_helper_progs.c
- src/py21cmfast/src/ps.c
- src/py21cmfast/src/recombinations.c
- tests/test_exceptions.py
Hey @steven-murray, I have taken a first stab at updating the granularity of the error coding and modifying the error messaging to try and make them a bit more informative. As I mentioned I did away with the `ParameterError` thing entirely, turning everything into a `FatalCError`.
Obviously the long `elif` code is ugly, but just temporary for now. Let me know what you think.
In some places I added to the output error through LOG, in particular including information known from some recent failings with the PhotonCons option (under certain parameter combinations).
Also, I have added some error checks for some AstroParams, causing it to exit with an informative error as to why.
I'm contemplating adding a warning for the other parameters when they are outside the usual parameter ranges we …
> More informative errors

- src/py21cmfast/wrapper.py
- tests/test_wrapper.py
Fix for bug #226 in making LFs with both ACHs + minihalos (`component=0`).
Added index for each redshift, and fixed array creation for Mhfunc_all to create the expected LFs. Added one test for LFs with minihalos.
> fix interpolation of LFs between ACHs and minihalos

- src/py21cmfast/src/UsefulFunctions.c
- src/py21cmfast/src/heating_helper_progs.c
- src/py21cmfast/src/ps.c
- src/py21cmfast/src/recombinations.c
Increase the accuracy of the GSL integration routine to resolve #225. May make the code ever so slightly slower, but should be negligible.
Additionally, update the error reporting for GSL errors to report the inbuilt GSL status code. This uses the already defined function that clearly I missed...
> Minor fixes to resolve gsl error in integration for sigma_z0

- .github/workflows/test_suite.yaml
- CHANGELOG.rst
- src/py21cmfast/inputs.py
- tests/test_input_structs.py
Closes #186
I went the route of issuing a warning whenever the user doesn't set this explicitly (because in principle this is API breaking, so we should at least warn users that it's happening). This warning can be removed in the next major version.
> fix: update use_interpolation_tables default with warning.

- setup.py
This adds fallback versions when downloading releases from Github.
Firstly, if you download an actual release, eg. `21cmFAST-3.1.5.tar.gz`, then it will get the version actually correct. If you just download the tarball from the master branch, eg. `21cmFAST.tar.gz`, then it will fallback to v0.0.0 without error.
> maint: fallback versions for downloading tarballs

- src/py21cmfast/wrapper.py
Fixes #277 
This should fix the behaviour mentioned in the above issue where data was being written even with `write=False`. The problem was that in every sub-function (eg. `initial_conditions()`), the `hooks` keyword was passed through, but not the `write` keyword. While the hooks initially get built as a dict with the correct behaviour (i.e. no "write" entry), on the second time the hooks is constructed, with `write=None`, it was assuming that function was being called directly and automatically inserting the write hook in, then passing that on.
> fix: issue with write=False not stopping I/O

- CHANGELOG.rst
- src/py21cmfast/_cfg.py
- src/py21cmfast/_utils.py
Fixes #80
This changes the string representation of `OutputStructs` and `StructWithDefaults` objects so that floats appear with a certain number of significant digits (configurable in global configuration). Primarily deals with the caching of redshifts (by default, it uses 4 significant digits, so the redshifts 6.001 and 6.000 would be considered different, but not 6.0001). 
A couple of things to think about:
1. I've applied the float rendering also to input structs, so eg. `HII_EFF_FACTOR=30.0` and `HII_EFF_FACTOR=30.001` would be considered the same. This could play a little havoc on MCMC routines (or other uses where a large database of randomly sampled parameters is chosen), so that the parameters change but the outputs don't, creating a "step-like" likelihood. To offset this, the …
> feat: floats in hashes now written to given sig figs

- .github/workflows/test_suite.yaml
Adds the CODECOV_TOKEN to avoid some of the upload errors from rate limits.
> ci: add codecov token due to rate limits

- CHANGELOG.rst
- environment_dev.yml
- src/py21cmfast/src/ps.c
Photon conservation correction could miss the initialisation step under an extreme scenario of a very early EoR and with low `Z_HEAT_MAX`. This PR adds in a check for this occurrence and initialises the requisite function if it has not already been initialised.
A fix for the specific example in #311. But not necessarily the broader issue of dealing with the brittle photon conservation correction
> Fix for the specific case in #311

- INSTALLATION.rst
- build_cffi.py
- environment_dev.yml
Added installation instructions for ubuntu reflecting my recent struggles (thank you @steven-murray )
Updated the 21cmfast environment YAML file to install python 3.9 and removed the gcc library package inside (since we found it was better to use a system installation of gcc)
Added --verbose flags in build_cffi,py
> Added ubuntu installation instructions

- src/py21cmfast/inputs.py
- src/py21cmfast/src/21cmFAST.h
- src/py21cmfast/src/Globals.h
- src/py21cmfast/src/HaloBox.c
- src/py21cmfast/src/interp_tables.c
- src/py21cmfast/src/ps.c
- tests/test_c_interpolation_tables.py
This solves issue (#371) by improving the hardcoded double power law in the stellar to halo mass relation stellar mass, so that it uses a flag option `USE_UPPER_STELLAR_TURNOVER` to switch it on or off, and two global params `UPPER_STELLAR_TURNOVER_MASS` and `UPPER_STELLAR_TURNOVER_INDEX` to define the power law segment. This is currently only implmented in the halo model since it will only effect galaxy-based observables (the effect on the radiative backgrounds is minimal).
I have also fixed some issues with the function `set_fixed_grids`, a function used to estimate the average quantities of halo properties in each cell. This is used either when we do not want stochastic halo samples but we still want to use the halo-based radiative backgrounds (`USE_HALO_FIELD=True` …
> Fixing some issues in the HaloBox struct and Mass Function Integrals.

- src/py21cmfast/wrapper.py
This small change explicitly purges the `HaloBox` fields which are no longer required at each timestep. The SFR at previous redshifts is used to construct the `XraySourceBox` but we don't need the other fields.
> Halobox memory improvements

- src/py21cmfast/src/HaloBox.c
This is a small change which affects cases where a user wants to cut halos from a catalogue before making a grid. For convenience we allow the setting of the mass to zero to acheive this, rather than creating a whole new output struct which needs to be `.compute()`d. This change cleans up the implementation of that case a little bit. Previously, if halos were cut, certain average quantities would not be calculated correctly, which influences the debug output, as well as the averaging of the mass turnover fields. Now cut halos are no longer counted as zero-mass halos in these averages.
> Allow halo catalogue cuts to output averages correctly

- src/py21cmfast/outputs.py
In the halobox requirements I missed a conversion from a `global_params` member to a `user_params` member. No integration test data had been made for this parameter so it was missed.
> fix urgent parameter error

- src/py21cmfast/outputs.py
- tests/test_high_level_io.py
Since the angular lightcone update, the `lightcone_distances` field has units. However these units are not saved and loaded from the HDF5 Files.
This is a quick fix which adds the units when required. It might be a better long-term idea to properly save the units of all quantities along with the values, however this will take more time, and currently you cannot call `lightcone_redshifts` on a lightcone loaded from file.
I have also added a `lightcone_redshift` check to `test_lightcone_roundtrip` to catch this in future.
> Lightcone distance unit fix

- src/py21cmfast/lightcones.py
- tests/test_lightconer.py
In some lightcone runs, I noticed a crash when the simulation was run at higher redshifts than the lightconer outputs. It seems that the case where we don't find any interpolation outputs in `make_lightcone_slices` yielded arguments in the wrong order, resulting in a KeyError when we index the lightcone. This has been fixed.
Before I merge, I would like to add to the tests to check for this, however we already run lightcones in the tests which have maximum redshifts below `Z_HEAT_MAX` and I'm having trouble figuring out why it doesn't crash there.
> fix return value order in make_lightcone_slices

- src/py21cmfast/inputs.py
- src/py21cmfast/outputs.py
- src/py21cmfast/src/21cmFAST.h
- src/py21cmfast/src/FindHaloes.c
- src/py21cmfast/src/HaloBox.c
- src/py21cmfast/src/IonisationBox.c
- src/py21cmfast/src/PerturbHaloField.c
- src/py21cmfast/src/SpinTemperatureBox.c
- src/py21cmfast/src/Stochasticity.c
- src/py21cmfast/src/UsefulFunctions.c
- src/py21cmfast/src/interp_tables.c
- src/py21cmfast/src/photoncons.c
- src/py21cmfast/src/ps.c
- src/py21cmfast/wrapper.py
- tests/test_halo_sampler.py
Currently WIP PR for adding the xray luminosity scatter, I am currently testing the outputs to make sure we get what we expect.
- Added another RNG field to `HaloField` and `PerturbHaloField` for the scatter in xray luminosity
- Added another field to the `HaloBox` and `XraySourceBox` to represent the xrays
- Added scaling relations for Metallicity, xray luminosity and mass-dependent SFR scatter to `HaloBox.c`
- Replaced the SFR field with the xray field in `SpinTemperature.c` for the xray calculations (lyman alpha / lyman werner still uses SFR)
- Refactored `HaloBox.c` to be more easily extendable and readable
> Lx scatter and Nikolic+2024 scaling relations

- src/py21cmfast/src/ps.c
There was an out-of-bounds array access in the TF_CLASS interpolations. I don't think this was ever actually tripped but I found it during the c-restructure since we can actually get good compiler warnings now.
> fix out-of-bounds access in TF_CLASS

- src/py21cmfast/cache_tools.py
- src/py21cmfast/inputs.py
- src/py21cmfast/outputs.py
- tests/test_high_level_io.py
There is currently a behaviour in `global_params.use()` which, unlike other parameter structures, raises an error when a keyword not in the parameter set is passed. This made it impossible to read in boxes from different versions that had differing parameters. I've made it behave like the other parameter sets now, which simply send out a warning.
However, to keep things safer, I've added a flag to the high-level output reading functions which ensure that all the parameters are there, if the flag is on and the parameters are mismatched it raises an error. if the flag is off it emits a warning detailing which parameters are missing / extra.
Tests have also been written to ensure the desired behaviour.
> Reading compatibility

- src/py21cmfast/src/LuminosityFunction.c
I had recently made changes to the HMF functions, which changed their definitions to be in-line with the conditional functions. These are dn / dlnM, and have a few constants removed to make the integral faster.
However, I forgot to include these changes in the function which calculates the luminosity function from the input parameters, so they were incorrect. This PR fixes the issue.
> fix UVLF from input parameters bugs

- src/py21cmfast/_utils.py
File loading keywords were confusing and the docstrings were incorrect.
I've changed the default reading behaviour to not load any arrays, and the keyword `arrays_to_load` or `keys` for `from_file` or `read` respectively works as follows:
Passing empty array `[]`: load nothing
Passing `None`: load everything
Passing a list of array names: load that subset of arrays
This is _technically_ API breaking so I'm placing this PR in v4-prep
> change default behaviour of from_file and read methods

- src/py21cmfast/src/HaloBox.c
- src/py21cmfast/src/IonisationBox.c
A few changes mainly for the upcoming database:
- Setting a constant mfp instead of the power-law fit, which resulted in kinks in reionisation history at z=6
- Using the filtered density instead of local when using the exponential filter, as done in (Davies+22)
- There are some questions here about what our model should be with this filter + recombinations but this choice seems better for now
- For unresolved halos in the sampler, use the Lagrangian density instead of Eulerian to be more consistent with the halo sampler. In future we also want to move these as particles with the 2LPT but that will take some time to develop so for now we assume they don't move.
> small changes for the upcoming database

- src/py21cmfast/src/InputParameters.c
- src/py21cmfast/src/Stochasticity.c
- src/py21cmfast/src/hmf.h
- src/py21cmfast/src/interp_tables.c
- src/py21cmfast/wrapper/cfuncs.py
- src/py21cmfast/wrapper/structs.py
- tests/conftest.py
- tests/test_c_interpolation_tables.py
- tests/test_drivers_lc.py
- tests/test_halo_sampler.py
- tests/test_singlefield.py
This PR will achieve two things:
- Moves most of the C backend access in the tests to wrapper/cfuncs.py to make them more intuitive
- changes the tolerances of tests to reflect what we actually expect from our functions. this mostly involves restricting the comparisons between interpolation tables and integrals to domains we actually care about, since most of these tests had <10^-3 errors in all bins except one near the critical collapse density, where it had 10^-1 error.
As such, tests (apart from integration tests of course) should all be passing.
> Fixing Tests

- src/py21cmfast/drivers/coeval.py
- src/py21cmfast/drivers/lightcone.py
- src/py21cmfast/wrapper/outputs.py
- tests/test_drivers_lc.py
I had previously included a third purging method of the ICs, `prepare_for_halos`. However since I needed the perturbing fields for the halos anyway, this was over-purging the arrays, resulting in unnecessary i/o.
This also includes a small fix to one of the tests which was taking longer than it should by using the wrong flag options.
> run lc tests with correct params, stop purging ics for halos

- src/py21cmfast/drivers/single_field.py
- src/py21cmfast/wrapper/outputs.py
This fixes two bugs which slipped through the tests when we removed recursion
- the hacky `XraySourceBox` construction has been changed to work with the new cached properties in the structs.
- `HaloField` required arrays have been updated
> Fix some bugs from most recent PR

- src/py21cmfast/run_templates.py
`InputParameters.from_template()` failed when supplied a filepath rather than template name due to the `create_params_from_template()` callable passing a string to `tomllib.load()` rather than a stream object. This has been fixed so that custom templates can now be supplied via their filepath.
> Fixed Template Filepath Reading

- src/py21cmfast/src/HaloBox.c
The prefactors to the integrated portions of the HaloBox field (either sub-sampler or fixed halo grids) were missing a term. This will have a minor effect on recombinations. Thanks @jordanflitter for finding this
> Fix gamma12 in sub-sampler HaloBox

- src/py21cmfast/drivers/lightcone.py
- src/py21cmfast/plotting.py
- src/py21cmfast/wrapper/inputs.py
- tests/test_plotting.py
- Updated global plotting script for the new output structures, which were still using lightcone.node_redshifts, And added a test to check for it.
- Added the turnover masses back into the possible lightcone global quantities
- Changed the default HALOMASS_CORRECTION variable to produce slightly better results with the default timestep
> Minor fixes to plotting scripts, adding turnover masses to global variables

- src/py21cmfast/src/HaloBox.c
- src/py21cmfast/src/IonisationBox.c
- src/py21cmfast/src/SpinTemperatureBox.c
- src/py21cmfast/src/_functionprototypes_wrapper.h
- src/py21cmfast/src/hmf.c
- src/py21cmfast/src/hmf.h
- src/py21cmfast/src/interp_tables.c
- src/py21cmfast/src/interp_tables.h
- src/py21cmfast/wrapper/cfuncs.py
- tests/test_c_interpolation_tables.py
Recently, we allowed the free parameter M_TURN to function in the minihalo model, as a lower limit set by supernovae feedback. Previously, the atomic cooling threshold was used both as the lower turnover for ACGs and the upper turnover for MCGs.
The correct behaviour would have been to separate these two turnovers entirely, where the upper turnover for MCGs is *always* the atomic cooling threshold, and the lower turnover for ACGs is set by the maximum of M_TURN and the cooling threshold. When implementing this new lower limit, I did not do this, meaning that the maximum of the cooling and M_TURN was used for both turnovers.
This PR fixes this issue by separating the two turnovers properly, as well as trying to clean up the table/integral functions a little to make them less confusing. The …
> Fixing Some Issues with New Mturn Paramterisation

- src/py21cmfast/src/SpinTemperatureBox.c
- src/py21cmfast/src/cosmology.c
- src/py21cmfast/src/filtering.c
- src/py21cmfast/src/filtering.h
- tests/test_cfuncs.py
- tests/test_segfaults.py
This is a cleanup of `cosmology.c` which had a lot of copy-pasted code and global parameter usage.
There are still some TODOs left involving double-checking all the transfer functions and removing a few old parts after I verify that they are no longer used/needed.
I've also added a speed criteria in `test_segfaults` to ensure that we aren't slowing the code down when making changes. First tests can be done using v3 values before perhaps moving to a different benchmarking method
> reorganise cosmology functions, setup future speed tests

- src/py21cmfast/src/IonisationBox.c
- src/py21cmfast/wrapper/outputs.py
This change was made to reduce used memory when `USE_HALO_FIELD=True`.
> Fcoll is 4D and Fcoll_MINI exists only if USE_HALO_FIELD=False

- .github/workflows/base_benchmarks.yml
PR #487 changed the installation strategy in our test workflows be much simpler, however they did not update the benchmark workflow, which now fails due to the missing environment file. This updates the installation in the bencher workflow to mimic the others.
> copy the test workflow installation to the benchmarks

- src/py21cmfast/io/caching.py
- src/py21cmfast/wrapper/inputs.py
- tests/conftest.py
- tests/test_caching.py
- tests/test_output_structs.py
- tests/test_singlefield.py
This fixes a couple of issues we had with caching:
- The path templates needed to be able to handle both the string wildcards, as well as possibly numerical values (hex for hashes, .4f for redshift etc), otherwise the `.format()` call would sometimes break
- It turns out that the python builtin `hash()` adds a random seed per session, making in unusable for hashing our input parameters
I have also moved some of the tests which dealt solely with the `OutputCache` into a new class within `test_caching.py` with some extra tests
> Fix caching issues

- build_cffi.py
Hello, this is a tentative PR to fix an installation issue when simply using pip to install the package.
During the installation this version tries to infer the compiler from the environment variable `CC` and only then falls back onto the compiler returned by `sysconfig.get_config_var("CC")`.
Since binary distributions of programs are so common, it is often the case that the compiler used to build python is not present on the system. But `sysconfig.get_config_var("CC")` returns just that - the compiler that was used to build this particular distribution. Using environment variables instead is a more flexible approach in my opinion.
Let me know if you are interested in integrating this PR and whether you require changes/tests/documentation.
> Detect c compiler more interactively

- build_cffi.py
This is a follow up to #480. This PR adds a log entry documenting why the value of `_compiler` was set, either because of an ENV var or because of the fallback specified by `sysconfig`.
Running `pip install -v ...` now produces output along the lines of:
```
...
DEBUG         See https://packaging.python.org/en/latest/guides/writing-pyproject-toml/#license for details.
DEBUG         ********************************************************************************
DEBUG
DEBUG !!
DEBUG   self._finalize_license_expression()
DEBUG Using compiler from environment variable 'CC': gcc
DEBUG running dist_info
DEBUG creating /home/remy/.cache/uv/builds-v0/.tmpSbFtEc/metadata_directory/21cmFAST.egg-info
DEBUG writing /home/remy/.cache/uv/builds-v0/.tmpSbFtEc/metadata_directory/21cmFAST.egg-info/PKG-IN …
```
> Log the compiler choice during installation

- .github/workflows/check-build.yml
- .github/workflows/deploy.yaml
- .github/workflows/release-draft.yml
- .github/workflows/run-tutorials.yaml
- .github/workflows/test_build_macos.yaml
- .github/workflows/test_suite.yaml
- CONTRIBUTING.rst
- docs/notes_for_developers.rst
This removes all CI references to production, renames "master" to "main" in them. and updates to developer docs a bit.
> rename master to main

- .github/workflows/deploy.yaml
This hopefully fixes the deployment to PyPI -- it installs fftw and gsl in the env before doing the build, and also makes it possible to run the deploy action when a release is _edited_, so we can just edit the already-existing release to re-trigger the deployment
> ci: fix deploy to install fftw and co

- src/py21cmfast/src/InitialConditions.c
- src/py21cmfast/src/PerturbField.c
- src/py21cmfast/wrapper/inputs.py
- tests/test_input_structs.py
This PR solves two bugs when `PERTURB_ON_HIGH_RES=True`:
1. In **InitialConditions.c**: if `PERTURB_ON_HIGH_RES=True` then `lowres_density` was not filled, thereby it was an array of all zeros. Now, `lowres_density` is always filled, regardless the value of `PERTURB_ON_HIGH_RES`. This change prevents a segmentation fault error when `HALO_STOCHASTICITY=False`, and there is a need to integrate over the conditional mass function where `lowres_density` serves as the conditional density (I am not sure why this segfault error happened in first place). NOTE: There is already an automatic error message that is thrown if `PERTURB_ON_HIGH_RES=True` and `HALO_STOCHASTICITY=True`, so this fix only handles the scenario where the latter is False.
2. In **PerturbField**: if `PERTURB_ALGORITHM='LINEAR'`, …
> fixed some bugs when PERTURB_ON_HIGH_RES=True

- setup.py
- src/py21cmfast/drivers/_param_config.py
- src/py21cmfast/drivers/coeval.py
- src/py21cmfast/drivers/single_field.py
- tests/test_caching.py
the `regenerate` keyword was double-popped in the `single_field_func` wrapper. This fixes the bug and adds a test using `pytest-mock` that the regeneration works as intended for single fields.
> Fix double regen pop

- src/py21cmfast/drivers/coeval.py
- src/py21cmfast/drivers/lightcone.py
- src/py21cmfast/drivers/single_field.py
- src/py21cmfast/io/caching.py
- src/py21cmfast/lightcones.py
- tests/test_drivers_coev.py
- tests/test_drivers_lc.py
- tests/test_singlefield.py
There were a few issues with the checkpointing system. Which was split into three levels:
1. Checking if an object existed already in the cache via the `single_field_func` wrapper
2. Determining the starting point of the run *from* the cache in `_obtain_starting_point_for_scrolling`
3. Checkpointing a lightcone object with `make_lightcone_checkpoint`
These changes fix the following issues with the checkpoints to make them more consistent:
- if `regenerate=True`, none of the checkpointing should run, this is now achieved by a check in (2) which sets the start to the first node
- (2) now checks if coeval `out_redshifts` or `lightcone._last_completed_node` is above the redshift of the cache completion.
- (3) now reads and writes to the correct lightcone indices, and tests have been made to …
> Fix checkpointing

- src/py21cmfast/io/caching.py
- tests/test_caching.py
`get_output_struct_at_z` currently uses the index `closest` instead of the actual redshift value `zs_of_kind[closest]`.
This leads to incorrect behaviour when the user passes a given `z` to this method.
> fix: small bug in caching

- src/py21cmfast/src/SpinTemperatureBox.c
- src/py21cmfast/wrapper/outputs.py
Thanks @jordanflitter for finding this. The mean sfr array has had the wrong (very large) shape for a while.
This PR also sets the MCG critical mass array to optional.
> fix array shape bug, make Mcrit array optional

- src/py21cmfast/wrapper/inputs.py
- tests/test_input_structs.py
Introduced a new error (and a test) if evolve_input_structs receives an invalid keyword.
> Raise error for invalid keyword in evolve_input_structs

- src/py21cmfast/io/caching.py
- tests/io/test_caching.py
This PR fixes #526. The problem was that the hash table didn't take `astro_options` into consideration, so two simulations with different `astro_options` had the same path in the cache.
I also included a test that verifies that the hash table is indeed modified when the parameters of the input structs are changed, or when either the random seed or `node_redshifts` are changed as well.
> Fixed hash table and included a new test
